/* Creature3D - Online Game Engine, Copyright (C) 2005 Wucaihua(26756325@qq.com)
 *
 * This library is free software; you can redistribute it and/or
 * modify it under the terms of the GNU Lesser General Public
 * License as published by the Free Software Foundation; either
 * version 2.1 of the License, or (at your option) any later version.
 *
 * This library is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the GNU
 * Lesser General Public License for more details.
*/
#include <CRNetApp/appCharacterUpdateMethod.h>
#include <CRNetApp/appNetLoader.h>
#include <CRNetApp/appNetPackets.h>
#include <CRNetApp/appNetPackets2.h>
#include <CRNetApp/appNetCallbacks.h>
#include <CRNetApp/appNetMethod.h>
#include <CRNetApp/appNetLogic.h>
#include <CRNetApp/appDataClass.h>
#include <CRNet\crConnectServerPacket.h>
#include <CRNet\crServerRefusePacket.h>
#include <CRNet\crErrorPacket.h>
#include <CRPhysics/crViewMatterObject.h>
#include <CRNetApp/appSingleGameMethod.h>
#include <CRNetApp/appSingleGameLogic.h>
#include <CRNetApp/appUIMethod.h>
#include <CRNetApp/appGlobalHandle.h>
#include <CRNetApp/appNodeCallbacks.h>
using namespace CRNet;
using namespace CRCore;
using namespace CRNetApp;

void CRNetApp::registerDataClass()
{
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crGlobalData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRunGameData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crGameClientData);
	//CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameRoleData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameMetierData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameBotData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameItemData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameNodeData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameSkillData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameWeaponData);

	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crBrainData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crCameraData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crCommandDlgData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRoomData);
}

void CRNetApp::registerHandleClass()
{
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsRuningMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetRunCodeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetRunCodeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetRunningMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetRunSceneIDMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetLoadingProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRunGameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRunGame2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRunNetGame2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginReturnMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDisconnectLoginMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRegisterAccountReturnMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginDownloadReturnMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginDownloadCaseMethod);
	
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDownloadedUpdatecfgLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSceneInfoLogic);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDownloadRoleFilesLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDownloadItemLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetMousePickLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDownloadItemChildLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBulletCollideLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBulletCollideSequenceLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBulletCollideSequence2Logic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWeaponFireLightLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBulletFlyParticleLogic);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWeaponFireSoundLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPlayerAI1Logic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraEffectLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crVolumeEffectLogic);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crHitTargetEffectLogic);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGameTaskCheckLogic);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaitNetReturnStreamLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUseThingParticleLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSlotTimerLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSlotProgressLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateSoundLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPlaySceneFxLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAttachCallbackMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPlaceLoadedNode2Logic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSelectRolePickLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateRoleInitLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateRoleSelectLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemEffectLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crParamItemEffectLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWeaponFireEffectLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBotEffectLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDynamicCollideExtraMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemDeadCheckMethod);

	////////Method
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRoleEventContainerMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSelectRolesEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQuickKeyPressedMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInitNetMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crFiniNetMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crConnectToLoginServerMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crConnectToLoginServerNewMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRegisterAccountMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crConnectToLoginServerNew2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crConnectToDownloadServerMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDisconnectDownloadServerMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginGameDownloadServerMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginGameSceneMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginGameScene2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDisconnectGameServerMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginChatMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvChatFriendListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvChatGroupListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvChatGroupMemberListMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crChatDataTransferEndMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvChatStateChangeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildFriendTreeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildGroupTreeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInfoTextMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crConnectToLoginServer2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRegisterAccountMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQueryOnlinePlayerListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crOnlinePlayerListMethod);
    CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAddChatFriendMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInsertToChatFriendTreeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateChatGroupMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInsertToChatGroupTreeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crChatWithFriendMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQueryChatGroupListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crChatGroupListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSendChatMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvFriendChatMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoadRecMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSendSceneChatMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSendSceneChat2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSendGameChatMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGameChatMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGameChat2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAddChatFriendSystemMsgMethod);

	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInitCheckAndDownloadFilesMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInitCheckFileListMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInitCheckEndMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGameListMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGameList2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetSelectedGameMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetSelectedGame2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExternSelectedGameMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEnterGameDownloadFilesMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvingDownLoadFileMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvingDownLoadFile2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckFileListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEnterGameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEnterSceneMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckRoleUpdatecfgMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEnterSceneSucessMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvedItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvedItem2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvedItemChildMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvedItemChild2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDownloadFileEndMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckAndDownloadFileMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaitLoginGameReturnMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginGameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginGameReturnMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNotifyMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGameRoleListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGameRoleList2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGameRoleListStreamMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvCreateRoleStreamMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvCreateMainRoleStreamMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetSelectRolePositionMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckAndLoadGameRolesMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetSelectedRoleMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetSelectedRole2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQuerySceneInfoMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQuerySceneInfo2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginSceneMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginSceneReturnMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsNetReturnSuccessMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsSuccessMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQueryRoleInfoMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvRoleInfoMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInitNetGameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crFinitNetGameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRunNetGameMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoadItemMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoadRoleDataMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSendToBotMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetPickTargetMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNodeMouseEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetControlMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRevertUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNodeCoordToItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemCoordToNodeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetMoveToTargetMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetMoveToTarget2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateRoleMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateRole2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQueryGameRoleListMethod);
    //CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaitStartGameMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crStartGameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetMouseControlViewMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRpgGameCharacterUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRpgGameCharacterStateChangeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRpgGameCharacterMoveChangeMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetStopMoveMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvStopMoveMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvItemRTDataMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvItemChildDataMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNodeInRangeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNodeOutRangeMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvCreateItemChildMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoadItemChildMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUseItemCheckMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUseItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetUseItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckCurrentAttackWeaponMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemUseMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemEspecialUseMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBotCollideMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetDamageFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetDamageFormula2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetDefendFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetDefendFormula2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetSpeedFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetHPFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetMPFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetHPRevertFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetMPRevertFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAttackSpeedFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvDamageMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvItemDeadMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowStateTextMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowHeadTextMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoadAndCloneNodeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateDecalMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateLightMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoadParticleMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoadSoundMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInPatrolTestMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCalcEnmityByDistRateMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetEnemy1Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSelectSkill1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPatrolMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvPatrolMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crHideBodyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvTargetExtraMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvUserExtraMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraLifeTimeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraDefendMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraGuiseMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraRadiusMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEnableBulletVolumeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNodeInBulletVolumeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCloseTargetItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvCloseTargetMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUseItemAndSendMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetControl2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvExperienceMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvExperience2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGoldMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGold2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvLvUpMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSinkMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crResetBotMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIRelivePlayerMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvRelivePlayerMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetKeyboardMouseModeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBulletCollideTestMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEnemyCheckMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRequestItemRTDataMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetRoleZMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTransportCollideMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvTransportMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExitSceneMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIExitSceneMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDisconnectSceneMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crParseExitCodeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crParseExitCode2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowStatsMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSnapImageMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecordMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUpdateRoleMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetNextLvExpMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemDoEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNodeDoEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crMyRoleDoEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crMyMetierEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAdvanceTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crReferTaskMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetReferTaskMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvNetReferTaskMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crClientReferTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGetTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvAdvanceTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvReferTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvTaskAwardItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvCorrectPositionMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetPickItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvNetPickItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInsertItemToBackPackMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUISaleItemMethod4
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSaleItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIRemoveItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRemoveItemFromBackPackMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildBackPackListMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaitNetReturnStreamLockMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIDropItem2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvDropItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildSaleItemListMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowPriceMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIBuyItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvBuyItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuyItemNotifyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUISetKeyboardMouseModeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetSaleItemMapMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIGetSaleItemMapMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSaleItemMapMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvDownLoadItemChildsMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvItemEventStreamMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvPlayerEventStreamMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvPlayerMetierEventStreamMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBeginExchangeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEndExchangeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIBeginExchangeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIEndExchangeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSaleItemMapChangeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUICloseTimerMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUINotifyMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvRefashSaleMapMethod);

	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetPriceFormula1Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildLearnSkillListMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUILearnSkillMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvLearnSkillMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvLearnSkillCreaterMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLearnSkillNotifyMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIAttrPointLRMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIAttrPointOKMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvAttrChangeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildSkillListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIEquipItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvEquipOnItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvComposeEquipCreaterMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEquipOnItemNotifyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildEquipOnListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIBuildBackPackListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIBuildSkillListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildQuickListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEquipValueMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUISetUseButtonTextMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUnEquipItemMethod);
    CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvUnEquipItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUnEquipItemNotifyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvEquipQuickMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUnEquipQuickMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvUnEquipQuickMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUnEquipQuickNotifyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUISetQuickKeyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSetQuickKeyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowItemInfoMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemInfoMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowTaskInfoMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowNextTaskInfoMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUseItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetUseThingMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvNetUseThingMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUTClientCureHPMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUTClientCureMPMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCancelUseSkillMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowTargetInfoMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUpdateTargetMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvCureHPMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvCureMPMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crServerRefuseMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowStaticTextMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowStaticText2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIAddGameGroupMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIAddGameFriendMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIChatWithFriendMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExitProgramMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRpgChangeCameraMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCameraShakeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUseItemProtectTimeUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTankChangeCameraMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIncreaseAimMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetAimUIMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvCreateRoleMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckGameRoleCountMethod);
    ////////////开房间式网游
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQuerySceneListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSceneListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetSelectedSceneMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQuerySceneRoomsMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSceneRoomsMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateSceneRoomMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateSceneRoomMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvCreateSceneRoomMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEnterRoomReturnMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPreEnterSceneRoomMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvEnterSceneRoomMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRoomInfoChangeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIRoomInfoUpdateMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLeaveSceneRoomMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvRoomPlayerDataMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crStartRoomGameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvStartRoomGameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvEndRoomGameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckAndRackEquipOnMeshMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLenFadeInitMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLenFadeInit2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLenFadeUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAttachCameraToNodeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crChangeCameraMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIfInVolumeNodeIsMeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBorrowCameraMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCameraBorrowUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crReturnCameraMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExecuteActionMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBotTurnToTargetMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemTurnToMeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crHideItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAdvanceSlotProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAutoPreviewImageMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNodeSetVisiableMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crMatrixNodeSetPositionMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetViewOffsetRangeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crStopSoundMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetNodeMaterialMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRemoveNodeMaterialMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRunFrequencyControlMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crMouseFrequencyControlMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetNodeColorMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crClientReadPathMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemCutTalkMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemCutSceneMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCutShowNodeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemSetActStateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crChangeActStateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemControllerMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDoItemControllerAndSendMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPlayerFindPathToMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvFindPathToMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvItemStateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPlayerTransportMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crITouchMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crITransportMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPlayerSetGuiseStateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGuiseStateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckItemTouchDistanceMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crThisIsMeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetItemCountInBackPackMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPlayerMoveToMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTankControllerMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDoTankControllerAndSendMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetControlTankMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCarMoveMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTankMoveMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRotateEmplacementLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSwitchCursorMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAttackMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvAttackMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBindWeaponMatrixMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUnBindWeaponMatrixMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowAimUIMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCarSlopeAdaptMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWheelAndTrackSpeedMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crViewPitchWobbleMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateTankAimMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRemoveRoleMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvRemoveRoleMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckGameRolesIsLoadedMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetSelectedRoomMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEnterSceneRoomMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvAboutToUseItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemUpdateTravelMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckPlayerGameNameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetReturnStreamMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crChangeWidgetTextColorMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crChangeWidgetTextColor2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crChangeWidgetTextColor3Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEditWidgetInputSizeCheckMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreatePlayerGameDataMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPlayerDataCreateStreamMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoadLocalSceneMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecordMousePosMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInvalidMousePosMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDrawDragRectMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRectSelectItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRectSelectNodeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaypointLinkMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaypointSaveMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaypointAutoSaveMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaypointLoadMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaypointLinkDrawMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaypointPannedMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWaypointDeleteMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetWaypointMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCameraFocusMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateSightMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSightFogInitMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSightFogUpdateMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvPathFindingMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPositionSyncMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvPositionSyncMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsMainAIMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crStopMyRolesMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCloseToSyncPositionMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAdvanceRoomProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTriggerSetRoomProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowSceneNodesMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crClientAddEyePointsMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crClientRemoveEyePointsMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDynamicCollideCheckMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSyncPosEmptyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDynamicChangePathMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQueryServerListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvConnectServerMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoginGameNewMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInitDownloadMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetDownloadThreadCountMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crFiniDownloadMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDownloadFilesMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreRestartMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCloseRunProtectedHandleMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDownloadUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoadingProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetFocusNodeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetDefFocusIndexMethod);
	
	//UI Method
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowNpcNameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowHyperTextMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateItemTalkMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowItemTalkMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowTaskMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIAwardItemTipInfoMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowTask2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetCurrentTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::cr3DUINotifyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::cr3DUINotify2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildSaleItemList2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIListControlTipInfoMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIBuyItem2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIBuyCountItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildLearnSkillList2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUILearnSkill2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildBackPackList2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildSkillList2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildQuickList2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildEquipOnList2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIItemListTipInfoMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUpdateRole2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUseItem2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUISaleItem2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUISaleCountItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIRemoveItem2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIEquipItem2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUnEquipQuick2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUISetQuickKey2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUnEquipItem2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUpdateExpProgressMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildTaskListMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUpdateMyInfoMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUpdateTargetInfoMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crMyHPTipInfoMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crMyMPTipInfoMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTargetHPTipInfoMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTargetMPTipInfoMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInitSceneMapMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUpdateMapInfoMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crMapZoomMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crMapHitMoveMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInitBuyCountDlgMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInitSaleCountDlgMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuyCountChangeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSaleCountChangeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIAttrPointLR2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIAttrPointOK2Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUpdateTaskTraceMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBackPackItemDragEventMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetStorageItemMapMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvStorageItemMapMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBuildStorageItemListMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInsertItemToStorageMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRemoveItemFromStorageMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvDepositItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvTakeoutItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIDepositItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIGetStorageItemMapMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUITakeoutItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSaleItemDragEventMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSkillItemDragEventMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crQuickItemDragEventMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEquipOnItemDragEventMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crStorageItemDragEventMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUpdateFaceframeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIUpdateHPProgressMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUIShowBattleTimeLimitMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUISwapEnableMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCommandEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEnableRTTMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTopViewRTTMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCameraViewRTTMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCollideMapRTTMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExportRTTMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAddRadioMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPageValueChangeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetRadioGroupValueMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRegisterTestAccountMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGameTaskUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShellExecuteMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crClipCursorMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsStartupLoadingMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crStartupLoadingInitMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crStartupLoadingProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetFpsControlMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crStartupSceneDownloadMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsStartupSceneDownloadingMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crBeginRunGameMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsWebLoginMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDoWebLoginMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetVolumeEnableMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsAlphaShadowDisabledMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crStopAllSceneFxMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLockKeyboardMouseMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetLightValidDistanceMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowEnginStatsMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRobotLoginGameMethod);
}

void CRNetApp::registerNetPacket()
{//如果没有注册packet将会导致发送数据包阻塞
    GNE::PacketParser::defaultRegisterPacket<CRNet::crUnKnownPacket>();
	GNE::PacketParser::defaultRegisterPacket<CRNet::crHeartJumpPacket>();
	GNE::PacketParser::defaultRegisterPacket<CRNet::crErrorPacket>();
	GNE::PacketParser::defaultRegisterPacket<CRNet::crConnectServerPacket>();

	GNE::PacketParser::defaultRegisterPacket<crAppServerRefusePacket>();
	GNE::PacketParser::defaultRegisterPacket<crAppLogoutPacket>();
	GNE::PacketParser::defaultRegisterPacket<crLogoutScenePacket>();
	//GNE::PacketParser::defaultRegisterPacket<crLoginPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crLoginChatPacket>();
	GNE::PacketParser::defaultRegisterPacket<crLoginParentPacket>();
	GNE::PacketParser::defaultRegisterPacket<crChatStateChangePacket>();
	GNE::PacketParser::defaultRegisterPacket<crCreateDataStreamPacket>();
	GNE::PacketParser::defaultRegisterPacket<crDataStreamPacket>();
	GNE::PacketParser::defaultRegisterPacket<crChatFriendListPacket>();
	GNE::PacketParser::defaultRegisterPacket<crChatGroupListPacket>();
	GNE::PacketParser::defaultRegisterPacket<crChatGroupMemberListPacket>();
	GNE::PacketParser::defaultRegisterPacket<crChatDataTransferEndPacket>();
	GNE::PacketParser::defaultRegisterPacket<crAddChatFriendPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRemoveChatFriendPacket>();
	GNE::PacketParser::defaultRegisterPacket<crChatPacket>();
	GNE::PacketParser::defaultRegisterPacket<crGroupChatPacket>();
	GNE::PacketParser::defaultRegisterPacket<crApplyJoinGroupPacket>();
	GNE::PacketParser::defaultRegisterPacket<crAcceptJoinGroupPacket>();
	GNE::PacketParser::defaultRegisterPacket<crNewMemberComingPacket>();
	GNE::PacketParser::defaultRegisterPacket<crAddChatGroupPacket>();
	GNE::PacketParser::defaultRegisterPacket<crAddGroupMemberPacket>();
	GNE::PacketParser::defaultRegisterPacket<crExitGroupPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRemoveGroupMemberPacket>();
	GNE::PacketParser::defaultRegisterPacket<crQueryOnlinePlayerListPacket>();
	GNE::PacketParser::defaultRegisterPacket<crQueryChatGroupListPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crRegisterAccountPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crDeleteAccountPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crUpdateAccountPasswordPacket>();
	GNE::PacketParser::defaultRegisterPacket<crCreateChatGroupPacket>();

	GNE::PacketParser::defaultRegisterPacket<crQueryGameListPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRecvGameListPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crLoginDownloadPacket>();
	GNE::PacketParser::defaultRegisterPacket<crDownloadFilePacket>();
	GNE::PacketParser::defaultRegisterPacket<crRequestFileStreamPacket>();
	GNE::PacketParser::defaultRegisterPacket<crFileStreamPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crLoginGamePacket>();
	GNE::PacketParser::defaultRegisterPacket<crQueryGameRoleListPacket>();
	GNE::PacketParser::defaultRegisterPacket<crCreateRolePacket>();
	//GNE::PacketParser::defaultRegisterPacket<crQuerySceneInfoPacket>();
	GNE::PacketParser::defaultRegisterPacket<crSceneServerInitPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRegisterSceneServerPacket>();
	GNE::PacketParser::defaultRegisterPacket<crSceneServerInitEndPacket>();
	GNE::PacketParser::defaultRegisterPacket<crQuerySceneItemPacket>();
	GNE::PacketParser::defaultRegisterPacket<crLoginScenePacket>();
	GNE::PacketParser::defaultRegisterPacket<crLoginScene2Packet>();
	GNE::PacketParser::defaultRegisterPacket<crLoginScene3Packet>();
	GNE::PacketParser::defaultRegisterPacket<crQueryRoleInfoPacket>();
	GNE::PacketParser::defaultRegisterPacket<crQueryRoleInfo2Packet>();
	//GNE::PacketParser::defaultRegisterPacket<crGetRoleZPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crPlayerInRangePacket>();
	//GNE::PacketParser::defaultRegisterPacket<crPlayerOutRangePacket>();
	GNE::PacketParser::defaultRegisterPacket<crRequestPlayerPacket>();
	GNE::PacketParser::defaultRegisterPacket<crItemInRangePacket>();
	GNE::PacketParser::defaultRegisterPacket<crItemOutRangePacket>();
	//GNE::PacketParser::defaultRegisterPacket<crNpcInRangePacket>();
	//GNE::PacketParser::defaultRegisterPacket<crNpcOutRangePacket>();
	GNE::PacketParser::defaultRegisterPacket<crRequestItemPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crRequestTaskAwardInfoPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPlayerEventPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crPlayerChildItemEventPacket>();
	GNE::PacketParser::defaultRegisterPacket<crItemEventPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crChildItemEventPacket>();
	GNE::PacketParser::defaultRegisterPacket<crSetClientRunningPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRemovePlayerPacket>();
	GNE::PacketParser::defaultRegisterPacket<crSaveItemDataPacket>();
	GNE::PacketParser::defaultRegisterPacket<crSaveItemStreamPacket>();
	GNE::PacketParser::defaultRegisterPacket<crSaveRoleDataPacket>();
	GNE::PacketParser::defaultRegisterPacket<crCreateItemChildPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPlayerServerEventPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPlayerServerMetierEventPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPlayerMetierEventPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crAddDamagePacket>();
	GNE::PacketParser::defaultRegisterPacket<crRequestItemRTDataPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRequestItemChildPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crAddTargetExtraPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crQueryAbstractItemPacket>();
	GNE::PacketParser::defaultRegisterPacket<crCreateTemporaryItemChildPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRemoveItemChildPacket>();
	GNE::PacketParser::defaultRegisterPacket<crSceneChatPacket>();
	GNE::PacketParser::defaultRegisterPacket<crGameChatPacket>();
	GNE::PacketParser::defaultRegisterPacket<crQuerySceneListPacket>();
	GNE::PacketParser::defaultRegisterPacket<crQuerySceneRoomsPacket>();
	GNE::PacketParser::defaultRegisterPacket<crCreateSceneRoomPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPreEnterSceneRoomPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crRoomPlayerDataPacket>();
	//GNE::PacketParser::defaultRegisterPacket<crLeaveSceneRoomPacket>();
	GNE::PacketParser::defaultRegisterPacket<crStartRoomGamePacket>();
	GNE::PacketParser::defaultRegisterPacket<crEndRoomGamePacket>();
	GNE::PacketParser::defaultRegisterPacket<crPauseRoomGamePacket>();
	GNE::PacketParser::defaultRegisterPacket<crRemoveRoomGamePacket>();
	GNE::PacketParser::defaultRegisterPacket<crRequestEmporiumPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRemoveRolePacket>();
	GNE::PacketParser::defaultRegisterPacket<crRoomGameTimePacket>();
	GNE::PacketParser::defaultRegisterPacket<crEnterSceneRoomPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRoomPlayerEventPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRoomAddMemberPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRoomRemoveMemberPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRoomSetPlayerGameDataPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRoomPlayerGameDataUpdatePacket>();
	GNE::PacketParser::defaultRegisterPacket<crRoomPlayerReadyPacket>();
	GNE::PacketParser::defaultRegisterPacket<crSavePlayerGameDataPacket>();
	GNE::PacketParser::defaultRegisterPacket<crCheckPlayerGameNamePacket>();
	GNE::PacketParser::defaultRegisterPacket<crCreatePlayerGameDataPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPlayerDataCreateStreamPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPlayerDataUpdateStreamPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPlayerDataEventPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPlayerDataSceneEventPacket>();
	GNE::PacketParser::defaultRegisterPacket<crEyePointsPacket>();
	GNE::PacketParser::defaultRegisterPacket<crCheckPlayerDelayTimePacket>();
	GNE::PacketParser::defaultRegisterPacket<crStopMyRolesPacket>();
	GNE::PacketParser::defaultRegisterPacket<crDBSavePacket>();
	GNE::PacketParser::defaultRegisterPacket<crServerListUpdatePacket>();
	GNE::PacketParser::defaultRegisterPacket<crServerListQueryPacket>();
	GNE::PacketParser::defaultRegisterPacket<crConnectServerInitPacket>();
	GNE::PacketParser::defaultRegisterPacket<crConnectServerUpdatePacket>();
	//GNE::PacketParser::defaultRegisterPacket<crConnectServerQueryPacket>();
	GNE::PacketParser::defaultRegisterPacket<crRoomEventPacket>();
	GNE::PacketParser::defaultRegisterPacket<crKickoffPlayerPacket>();
	GNE::PacketParser::defaultRegisterPacket<crSetGamelogPathPacket>();
	GNE::PacketParser::defaultRegisterPacket<crThrowServerPacket>();
	GNE::PacketParser::defaultRegisterPacket<crServerNeedRestartPacket>();
	GNE::PacketParser::defaultRegisterPacket<crClientReconnectPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPlayerDataEventZipPacket>();
	GNE::PacketParser::defaultRegisterPacket<crPlayerDataSceneEventZipPacket>();
	GNE::PacketParser::defaultRegisterPacket<crQueryGameInfoPacket>();
	GNE::PacketParser::defaultRegisterPacket<crShutDownServerPacket>();

	//insertCookID(crLoginPacket::ID);
	//insertCookID(crLoginChatPacket::ID);
	//insertCookID(crLoginGamePacket::ID);
	insertCookID(crLoginScenePacket::ID);
	//insertCookID(crLoginDownloadPacket::ID);
	insertCookID(crRemoveRolePacket::ID);

	//insertZipID(crRecvGameListPacket::ID);
	insertZipID(crDataStreamPacket::ID);
	insertZipID(crFileStreamPacket::ID);
	//insertZipID(crChatPacket::ID);
	//insertZipID(crSceneChatPacket::ID);
	//insertZipID(crGameChatPacket::ID);
	insertZipID(crServerListQueryPacket::ID);
	insertZipID(crPlayerDataEventZipPacket::ID);
	insertZipID(crPlayerDataSceneEventZipPacket::ID);

	if(crNetContainer::getInstance()->getMainNetType() == GameServer)
	{//涉及到数据库更新操作采用异步延时处理
		insertAsynParseID(crCreateRolePacket::ID);
		insertAsynParseID(crCreateItemChildPacket::ID);
		//insertAsynParseID(crSaveItemDataPacket::ID);
		//insertAsynParseID(crSaveRoleDataPacket::ID);
		//insertAsynParseID(crRemoveItemChildPacket::ID);
		insertAsynParseID(crRemoveRolePacket::ID);
		insertAsynParseID(crCreatePlayerGameDataPacket::ID);
		insertAsynParseID(crQueryRoleInfo2Packet::ID);
	}
	insertAsynParseID(crServerListUpdatePacket::ID);
	insertAsynParseID(crConnectServerInitPacket::ID);
	insertAsynParseID(crConnectServerUpdatePacket::ID);
	//insertAsynParseID(crDBSavePacket::ID);
	//insertZipID(crDBSavePacket::ID);
}

void CRNetApp::registerNetCallbacks()
{
	CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crLoginServerCallback);
	CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crLoginConnectServerCallback);
	CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crChatServerCallback);
	CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crChatConnectServerCallback);
	CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crParentServerCallback);
    CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crDownloadServerCallback);
    CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crDownloadConnectServerCallback);	
	CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crGameServerCallback);
	CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crGameConnectServerCallback);
	CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crSceneServerCallback);
	CRNet::crNetCallbackManager::RegisterNetCallbackProxy(new crDBServerCallback);
}

void CRNetApp::registerServerDataClass()
{
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crGlobalData);
	//CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameRoleData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameMetierData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameBotData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameItemData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRpgGameSkillData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crSceneServerData);
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crRoomData);
}

void CRNetApp::registerServerHandleClass()
{
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNpcEnmityTestLogic);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNpcAI1Logic);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSceneItemListMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvRoleInfo2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvMainRoleMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crServerCheckRoleDataMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPlayerInRangeTestMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemInRangeTestMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRoomPlayerInRangeTestMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRoomItemInRangeTestMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetControlMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crServerItemMoveMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRevertUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvStopMoveMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNodeCollideWithItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDamageCollideFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetDamageFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetDamageFormula2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetDefendFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetDefendFormula2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetSpeedFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetHPFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetMPFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetHPRevertFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetMPRevertFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAttackSpeedFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAddDamageFormula1Method);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLoadItemChildMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInPatrolTestMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCalcEnmityByDistRateMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetEnemy1Method);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSelectSkill1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPatrolMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvPatrolMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUseItemCheckMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crServerUseItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetServerUseItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraLifeTimeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraDefendMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraGuiseMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crExtraRadiusMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crServerCloseTargetItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUseItemAndSendMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetControl2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetItemRTDataMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetItemChildDataMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNpcDeadMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAddExperienceMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAddExperience2Method);
    CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAddGoldMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAddGold2Method);
    CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLvUpFormula1Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDeadEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvRelivePlayerMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEnemyCheckMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvTransportMethod);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crAdvanceTaskMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crReferTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crKillerMetierEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGetTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvAdvanceTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvReferTaskMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvNetReferTaskMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTaskAwardMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvAbstractItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDropItemUpdateMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvNetPickItemMethod);
	////CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInsertItemToBackPackMethod);
	////CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSaleItemMethod);
	////CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRemoveItemFromBackPackMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvDropItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvBuyItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSaleItemMapMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvDownLoadItemChildsMethod);
	////CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvBeginExchangeMethod);
	////CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvEndExchangeMethod);
	////CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRefashSaleMapMethod);
	////CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetPriceFormula1Method);
	////CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvLearnSkillMethod);
	////CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crLearnSkillCreaterMethod);
	////CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvAttrChangeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvEquipOnItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crComposeEquipCreaterMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crEquipValueMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvUnEquipItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvEquipQuickMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvUnEquipQuickMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvSetQuickKeyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvNetUseThingMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUTCureHPMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUTCureMPMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCureHPCollideMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCureMPCollideMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCureHPMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCureMPMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUTTransportToBaseMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUseItemProtectTimeUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crServerReadPathMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCloseToSyncPositionMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvFindPathToMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvItemStateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvGuiseStateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvStorageItemMapMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInsertItemToStorageMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRemoveItemFromStorageMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvDepositItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvTakeoutItemMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNetControlTankMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCarMoveMethod);//crServerMoveMethod
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTankMoveMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvAttackMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvAboutToUseItemMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemUpdateTravelMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRunFrequencyControlMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvCreateSightMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvPathFindingMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCheckPlayerDelayTimeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPositionSyncMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvPositionSyncMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crUseItemRecordMapUpdateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsMainAIMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crInitRoomProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGetRoomProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvAdvanceRoomProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetRoomProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crReliveItemsMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crKillItemsMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crNextRoomProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRoomSetRoomProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRecvTriggerSetRoomProgressMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRoomProgressEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crScenarioEventMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIFItemsDeadMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetRoomAutoStartMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetRemainTimeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsRoomPlayerEmptyMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSendRoomTimeRemainMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRoomUpdate2Method);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crItemDeadCheckMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crWriteServerInfoMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetGamelogPathMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crRechargeDisposeMethod);
	//CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crMoneyChangeMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGainBirthPointMethod);
}

void CRNetApp::registerVRHandleClass()
{
	//单机游戏
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCreateSingleGameDataMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSingleGameItemInRangeTestMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSingleGameRecvItemRTDataMethod);
	//VR_ICBC
	CRCore::crDataManager::RegisterDataProxy(new CRNetApp::crTalkChooseUIData);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crVR_ICBCMousePickLogic);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowShelfUILogic);

	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crTransportCommandMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crDoTransportCommandMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowTalkChooseMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowTalkPreviewMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowTalkTextMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crPlayerChooseTalkMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCutTalkMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crCutSceneMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crSetSpecialActStateMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crShowTextMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crGlobalValue_ICBCMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crIsInterveneMethod);
	CRCore::crHandleManager::RegisterHandleProxy(new CRNetApp::crVR_ICBCChangeRoleMethod);
}

void CRNetApp::registerEventCallback()
{
	CRCore::crEventCallbackManager::RegisterEventCallbackProxy(new CRNetApp::crDecalUpdateCallback);
	CRCore::crEventCallbackManager::RegisterEventCallbackProxy(new CRNetApp::crAutoTransCallback);
	CRCore::crEventCallbackManager::RegisterEventCallbackProxy(new CRNetApp::crActFxCallback);
}